### ISSUE TITLE
Unrecognized function or variable 'function_loading_ply_file'.

### ISSUE THREAD

**Issue by jhz07** [HandongHCI/3D_Anthro#1]
Hello, thank you for the 3D Anthropometric library. 
I was trying to test this library, however, the function _"function_loading_ply_file"_ was not found by the _"example_main"_ file. I have tried to look for the same function in other directories provided with this library but there is no function by this name? Can you please help me with it?

**Comment by HandongHCI** [comment]
Dear jhz07,
Thank you for your notice! I recently updated file names, but those updates were not applied to example files. I just updated the example files and you may run without errors! Please let me know if you meet further issues! Thanks!
